services:
    essoscraper:
        container_name: sofagasbuddy
        image: sofagasbuddy-scraper
        ports:
            - 9999:9999
        environment:
            - SSN=622320286
            - VRN=S TB5368
            - REFRESH_INTERVAL=3600
        restart: unless-stopped
